version: "3.1"

services:

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/jblantz/pingidentity-devops-getting-started.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - SERVER_PROFILE_PARENT=LICENSE
      - SERVER_PROFILE_LICENSE_URL=https://github.com/jblantz/pingidentity-devops-getting-started.git
      - SERVER_PROFILE_LICENSE_PATH=licenses/pingdirectory
      - TOPOLOGY_PREFIX=03-full-stack_pingdirectory_
      - VERBOSE=true
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal

  
networks:
    pingnet-internal:
    pingnet-dmz:
